contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 0
- 1000
- 2
- 2
seqLen: 41
stopOnFail: false
testLimit: 1000000000
timeout: 300
