contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.72
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 1000
- 0
- 1000
- 1
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 300
