contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.56
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 2000
- 1
- 2000
- 2000
seqLen: 16
stopOnFail: false
testLimit: 1000000000
timeout: 30
