contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.3
filterBlacklist: true
filterFunctions: []
mutConsts:
- 2000
- 0
- 2
- 0
seqLen: 298
stopOnFail: false
testLimit: 1000000000
timeout: 300
