contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 0
- 1
- 1000
- 2000
seqLen: 241
stopOnFail: false
testLimit: 1000000000
timeout: 30
