contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions: []
mutConsts:
- 0
- 2000
- 1000
- 2000
seqLen: 61
stopOnFail: false
testLimit: 1000000000
timeout: 300
