contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.59
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 0
- 0
- 2000
- 2
seqLen: 170
stopOnFail: false
testLimit: 1000000000
timeout: 30
