contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.75
filterBlacklist: true
filterFunctions: []
mutConsts:
- 1000
- 2
- 1
- 1
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 300
