contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.59
filterBlacklist: true
filterFunctions: []
mutConsts:
- 3
- 0
- 0
- 0
seqLen: 296
stopOnFail: false
testLimit: 1000000000
timeout: 300
