contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 1
- 1
- 2
- 0
seqLen: 294
stopOnFail: false
testLimit: 1000000000
timeout: 300
