contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.06
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 2
- 0
- 2
- 0
seqLen: 150
stopOnFail: false
testLimit: 1000000000
timeout: 300
