contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions: []
mutConsts:
- 0
- 0
- 1
- 1000
seqLen: 275
stopOnFail: false
testLimit: 1000000000
timeout: 300
