contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.82
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 2000
- 0
- 2
- 0
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 300
