contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.92
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 2
- 2
- 2
- 2000
seqLen: 127
stopOnFail: false
testLimit: 1000000000
timeout: 300
