contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.57
filterBlacklist: true
filterFunctions: []
mutConsts:
- 3
- 3
- 2
- 2000
seqLen: 240
stopOnFail: false
testLimit: 1000000000
timeout: 300
