contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions: []
mutConsts:
- 2000
- 2
- 1
- 2000
seqLen: 39
stopOnFail: false
testLimit: 1000000000
timeout: 300
