contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.58
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 1000
- 1000
- 2
- 3
seqLen: 219
stopOnFail: false
testLimit: 1000000000
timeout: 300
