contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions: []
mutConsts:
- 2000
- 2000
- 2000
- 0
seqLen: 148
stopOnFail: false
testLimit: 1000000000
timeout: 300
