contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.74
filterBlacklist: true
filterFunctions: []
mutConsts:
- 3
- 1
- 2
- 0
seqLen: 39
stopOnFail: false
testLimit: 1000000000
timeout: 300
