contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.09
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 0
- 2000
- 1000
- 1000
seqLen: 61
stopOnFail: false
testLimit: 1000000000
timeout: 300
