contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.9
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 2
- 0
- 1
- 0
seqLen: 26
stopOnFail: false
testLimit: 1000000000
timeout: 300
