contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.78
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 3
- 2000
- 1000
- 2
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 300
