contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.83
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 2000
- 3
- 3
- 1
seqLen: 204
stopOnFail: false
testLimit: 1000000000
timeout: 300
