contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.78
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 1000
- 2
- 2000
- 1
seqLen: 205
stopOnFail: false
testLimit: 1000000000
timeout: 300
