contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 0
- 0
- 2
- 1
seqLen: 175
stopOnFail: false
testLimit: 1000000000
timeout: 300
