contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.47
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 1000
- 0
- 0
- 2
seqLen: 125
stopOnFail: false
testLimit: 1000000000
timeout: 300
