contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.82
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 1000
- 2
- 0
- 2000
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 300
