contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.29
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 1000
- 1
- 1
- 0
seqLen: 17
stopOnFail: false
testLimit: 1000000000
timeout: 30
