contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.87
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 0
- 2
- 1
- 1
seqLen: 44
stopOnFail: false
testLimit: 1000000000
timeout: 300
