contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 1000
- 1
- 0
- 0
seqLen: 262
stopOnFail: false
testLimit: 1000000000
timeout: 300
