contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.37
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 1
- 1000
- 2000
- 1000
seqLen: 88
stopOnFail: false
testLimit: 1000000000
timeout: 300
