contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.24
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 2
- 2
- 3
- 2000
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 300
