contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.08
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 2
- 3
- 2000
- 3
seqLen: 217
stopOnFail: false
testLimit: 1000000000
timeout: 300
