contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.3
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 0
- 1000
- 1
- 2
seqLen: 45
stopOnFail: false
testLimit: 1000000000
timeout: 300
