contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 1000
- 1000
- 1
- 2
seqLen: 97
stopOnFail: false
testLimit: 1000000000
timeout: 300
