contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.26
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 1
- 1000
- 3
- 1000
seqLen: 74
stopOnFail: false
testLimit: 1000000000
timeout: 300
