contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.79
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 1
- 0
- 2
- 0
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 300
