contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.54
filterBlacklist: true
filterFunctions: []
mutConsts:
- 2000
- 1
- 3
- 1000
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 300
