contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.65
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 2000
- 2000
- 1000
- 0
seqLen: 261
stopOnFail: false
testLimit: 1000000000
timeout: 300
