contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.13
filterBlacklist: true
filterFunctions: []
mutConsts:
- 2
- 0
- 3
- 1000
seqLen: 134
stopOnFail: false
testLimit: 1000000000
timeout: 300
