contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.44
filterBlacklist: true
filterFunctions: []
mutConsts:
- 1000
- 2000
- 1
- 0
seqLen: 127
stopOnFail: false
testLimit: 1000000000
timeout: 300
