contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.24
filterBlacklist: true
filterFunctions: []
mutConsts:
- 3
- 1000
- 3
- 3
seqLen: 295
stopOnFail: false
testLimit: 1000000000
timeout: 300
