contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.21
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 1
- 0
- 1
- 1
seqLen: 170
stopOnFail: false
testLimit: 1000000000
timeout: 300
