contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.35
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 3
- 0
- 1
- 2000
seqLen: 204
stopOnFail: false
testLimit: 1000000000
timeout: 300
