contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.67
filterBlacklist: true
filterFunctions: []
mutConsts:
- 2000
- 0
- 1000
- 2000
seqLen: 134
stopOnFail: false
testLimit: 1000000000
timeout: 30
