contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.17
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 3
- 1000
- 2000
- 2000
seqLen: 23
stopOnFail: false
testLimit: 1000000000
timeout: 300
