contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions: []
mutConsts:
- 3
- 1
- 1
- 3
seqLen: 212
stopOnFail: false
testLimit: 1000000000
timeout: 300
