contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.88
filterBlacklist: true
filterFunctions: []
mutConsts:
- 3
- 1
- 1
- 0
seqLen: 27
stopOnFail: false
testLimit: 1000000000
timeout: 300
