contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.63
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 1000
- 0
- 1
- 1
seqLen: 222
stopOnFail: false
testLimit: 1000000000
timeout: 300
