contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.49
filterBlacklist: true
filterFunctions: []
mutConsts:
- 2
- 1
- 0
- 2
seqLen: 245
stopOnFail: false
testLimit: 1000000000
timeout: 300
