contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.06
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 0
- 1
- 1
- 1
seqLen: 55
stopOnFail: false
testLimit: 1000000000
timeout: 300
