contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 2000
- 3
- 2000
- 1
seqLen: 80
stopOnFail: false
testLimit: 1000000000
timeout: 300
