contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.15
filterBlacklist: true
filterFunctions: []
mutConsts:
- 0
- 1000
- 2
- 1
seqLen: 296
stopOnFail: false
testLimit: 1000000000
timeout: 300
