contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.56
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 1000
- 3
- 0
- 2
seqLen: 70
stopOnFail: false
testLimit: 1000000000
timeout: 300
