contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.14
filterBlacklist: true
filterFunctions: []
mutConsts:
- 2000
- 2000
- 3
- 1000
seqLen: 257
stopOnFail: false
testLimit: 1000000000
timeout: 300
