contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.15
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 1
- 3
- 3
- 3
seqLen: 196
stopOnFail: false
testLimit: 1000000000
timeout: 300
