contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.78
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 2
- 2
- 2000
- 0
seqLen: 158
stopOnFail: false
testLimit: 1000000000
timeout: 300
