contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.66
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 1000
- 3
- 2
- 2
seqLen: 212
stopOnFail: false
testLimit: 1000000000
timeout: 300
