contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.1
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 2
- 3
- 1
- 1000
seqLen: 273
stopOnFail: false
testLimit: 1000000000
timeout: 300
