contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.81
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 0
- 1
- 3
- 0
seqLen: 235
stopOnFail: false
testLimit: 1000000000
timeout: 300
