contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.1
filterBlacklist: true
filterFunctions: []
mutConsts:
- 0
- 1000
- 3
- 3
seqLen: 120
stopOnFail: false
testLimit: 1000000000
timeout: 300
