contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.56
filterBlacklist: true
filterFunctions: []
mutConsts:
- 2
- 3
- 2
- 1
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 300
