contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.64
filterBlacklist: true
filterFunctions: []
mutConsts:
- 1
- 0
- 3
- 2000
seqLen: 225
stopOnFail: false
testLimit: 1000000000
timeout: 300
