contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.83
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 2000
- 2
- 0
- 1
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 300
