contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.82
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 0
- 1000
- 2000
- 0
seqLen: 199
stopOnFail: false
testLimit: 1000000000
timeout: 300
