contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.72
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 2000
- 1
- 1000
- 3
seqLen: 21
stopOnFail: false
testLimit: 1000000000
timeout: 300
