contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.73
filterBlacklist: true
filterFunctions: []
mutConsts:
- 1
- 2000
- 0
- 0
seqLen: 26
stopOnFail: false
testLimit: 1000000000
timeout: 300
