contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.3
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 3
- 2000
- 2000
- 3
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 30
