contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.9
filterBlacklist: true
filterFunctions: []
mutConsts:
- 2
- 3
- 3
- 0
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 300
