contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.85
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 2
- 3
- 1
- 1000
seqLen: 23
stopOnFail: false
testLimit: 1000000000
timeout: 300
