contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.17
filterBlacklist: true
filterFunctions: []
mutConsts:
- 3
- 1000
- 2
- 1
seqLen: 256
stopOnFail: false
testLimit: 1000000000
timeout: 300
