contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.66
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 3
- 1000
- 0
- 2000
seqLen: 204
stopOnFail: false
testLimit: 1000000000
timeout: 30
