contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.67
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 1
- 2000
- 2000
- 3
seqLen: 271
stopOnFail: false
testLimit: 1000000000
timeout: 300
