contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.16
filterBlacklist: true
filterFunctions: []
mutConsts:
- 3
- 2
- 1000
- 3
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 300
