contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.23
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 1000
- 2000
- 2
- 3
seqLen: 269
stopOnFail: false
testLimit: 1000000000
timeout: 300
