contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.92
filterBlacklist: true
filterFunctions: []
mutConsts:
- 2000
- 3
- 3
- 1
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 30
