contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.16
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 3
- 3
- 0
- 1000
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 30
