contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.64
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 1000
- 2000
- 2000
- 1000
seqLen: 88
stopOnFail: false
testLimit: 1000000000
timeout: 300
