contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions: []
mutConsts:
- 1
- 3
- 2
- 1
seqLen: 271
stopOnFail: false
testLimit: 1000000000
timeout: 300
