contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.24
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 3
- 2000
- 0
- 3
seqLen: 54
stopOnFail: false
testLimit: 1000000000
timeout: 300
