contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 0
- 0
- 2
- 2000
seqLen: 57
stopOnFail: false
testLimit: 1000000000
timeout: 30
