contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.91
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 2000
- 0
- 2
- 3
seqLen: 63
stopOnFail: false
testLimit: 1000000000
timeout: 300
