contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.79
filterBlacklist: true
filterFunctions: []
mutConsts:
- 2000
- 3
- 0
- 0
seqLen: 255
stopOnFail: false
testLimit: 1000000000
timeout: 300
