contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.66
filterBlacklist: true
filterFunctions: []
mutConsts:
- 3
- 2
- 1000
- 1
seqLen: 194
stopOnFail: false
testLimit: 1000000000
timeout: 300
