contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.82
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 1000
- 3
- 2
- 1
seqLen: 104
stopOnFail: false
testLimit: 1000000000
timeout: 300
