contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.88
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 1
- 3
- 2
- 2000
seqLen: 14
stopOnFail: false
testLimit: 1000000000
timeout: 300
