contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.55
filterBlacklist: true
filterFunctions: []
mutConsts:
- 2
- 2000
- 3
- 0
seqLen: 230
stopOnFail: false
testLimit: 1000000000
timeout: 300
