contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.72
filterBlacklist: true
filterFunctions: []
mutConsts:
- 2000
- 1000
- 2000
- 1
seqLen: 246
stopOnFail: false
testLimit: 1000000000
timeout: 300
