contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.39
filterBlacklist: true
filterFunctions: []
mutConsts:
- 2000
- 2000
- 0
- 3
seqLen: 104
stopOnFail: false
testLimit: 1000000000
timeout: 300
