contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.83
filterBlacklist: true
filterFunctions: []
mutConsts:
- 3
- 0
- 1
- 1
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 300
