contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.84
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 2
- 3
- 0
- 1
seqLen: 151
stopOnFail: false
testLimit: 1000000000
timeout: 300
