contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.94
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 1
- 1
- 0
- 1
seqLen: 224
stopOnFail: false
testLimit: 1000000000
timeout: 300
