contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 3
- 1
- 2
- 1
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 30
