contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.59
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 2
- 2
- 1000
- 0
seqLen: 233
stopOnFail: false
testLimit: 1000000000
timeout: 300
