contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.25
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 2000
- 1000
- 2
- 2
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 300
