contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.09
filterBlacklist: true
filterFunctions: []
mutConsts:
- 0
- 2
- 1
- 2000
seqLen: 258
stopOnFail: false
testLimit: 1000000000
timeout: 300
