contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.44
filterBlacklist: true
filterFunctions: []
mutConsts:
- 1
- 1000
- 0
- 2
seqLen: 174
stopOnFail: false
testLimit: 1000000000
timeout: 300
