contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.39
filterBlacklist: true
filterFunctions: []
mutConsts:
- 2
- 0
- 2
- 1
seqLen: 145
stopOnFail: false
testLimit: 1000000000
timeout: 300
