contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.89
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 2
- 2
- 2
- 1
seqLen: 281
stopOnFail: false
testLimit: 1000000000
timeout: 300
