contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.53
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 1
- 2000
- 3
- 0
seqLen: 85
stopOnFail: false
testLimit: 1000000000
timeout: 300
