contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.18
filterBlacklist: true
filterFunctions: []
mutConsts:
- 2000
- 2000
- 0
- 2
seqLen: 31
stopOnFail: false
testLimit: 1000000000
timeout: 300
