contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.62
filterBlacklist: true
filterFunctions: []
mutConsts:
- 1
- 1
- 2000
- 1000
seqLen: 53
stopOnFail: false
testLimit: 1000000000
timeout: 300
