contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions: []
mutConsts:
- 1000
- 1
- 0
- 2
seqLen: 290
stopOnFail: false
testLimit: 1000000000
timeout: 300
