contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions: []
mutConsts:
- 2
- 2
- 2000
- 3
seqLen: 216
stopOnFail: false
testLimit: 1000000000
timeout: 300
