contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.26
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 1
- 2
- 3
- 0
seqLen: 231
stopOnFail: false
testLimit: 1000000000
timeout: 30
