contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.62
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 0
- 1
- 2
- 2000
seqLen: 148
stopOnFail: false
testLimit: 1000000000
timeout: 300
