contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.52
filterBlacklist: true
filterFunctions: []
mutConsts:
- 2000
- 1000
- 2000
- 3
seqLen: 235
stopOnFail: false
testLimit: 1000000000
timeout: 300
