contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.47
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 1
- 1
- 3
- 1
seqLen: 252
stopOnFail: false
testLimit: 1000000000
timeout: 300
