contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 2000
- 2000
- 2
- 2
seqLen: 174
stopOnFail: false
testLimit: 1000000000
timeout: 30
