contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.64
filterBlacklist: true
filterFunctions: []
mutConsts:
- 1000
- 1000
- 2000
- 2
seqLen: 21
stopOnFail: false
testLimit: 1000000000
timeout: 30
