contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.05
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 1000
- 1
- 1
- 2000
seqLen: 279
stopOnFail: false
testLimit: 1000000000
timeout: 300
