contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.6
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 3
- 1
- 3
- 0
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 300
