contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.61
filterBlacklist: true
filterFunctions: []
mutConsts:
- 0
- 2000
- 3
- 1000
seqLen: 83
stopOnFail: false
testLimit: 1000000000
timeout: 300
