contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions: []
mutConsts:
- 3
- 2000
- 1000
- 2
seqLen: 286
stopOnFail: false
testLimit: 1000000000
timeout: 300
