contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions: []
mutConsts:
- 2000
- 2
- 0
- 0
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 30
