contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 0
- 3
- 0
- 1000
seqLen: 172
stopOnFail: false
testLimit: 1000000000
timeout: 300
