contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.73
filterBlacklist: true
filterFunctions: []
mutConsts:
- 3
- 1
- 1
- 1000
seqLen: 214
stopOnFail: false
testLimit: 1000000000
timeout: 300
