contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.24
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 0
- 1
- 2
- 1
seqLen: 240
stopOnFail: false
testLimit: 1000000000
timeout: 300
