contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.09
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 3
- 2
- 1000
- 3
seqLen: 65
stopOnFail: false
testLimit: 1000000000
timeout: 300
