contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.84
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 3
- 1
- 1000
- 2000
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 300
