contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 0
- 2000
- 1000
- 1
seqLen: 126
stopOnFail: false
testLimit: 1000000000
timeout: 300
