contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.16
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 3
- 0
- 1000
- 2000
seqLen: 136
stopOnFail: false
testLimit: 1000000000
timeout: 30
