contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 2000
- 1
- 0
- 3
seqLen: 21
stopOnFail: false
testLimit: 1000000000
timeout: 300
