contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.46
filterBlacklist: true
filterFunctions: []
mutConsts:
- 0
- 1000
- 0
- 2
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 300
