contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.57
filterBlacklist: true
filterFunctions: []
mutConsts:
- 0
- 3
- 1000
- 2000
seqLen: 159
stopOnFail: false
testLimit: 1000000000
timeout: 30
