contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.85
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 1
- 2
- 0
- 0
seqLen: 33
stopOnFail: false
testLimit: 1000000000
timeout: 30
