contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.49
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 2
- 3
- 2
- 3
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 300
