contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.68
filterBlacklist: true
filterFunctions: []
mutConsts:
- 2000
- 1000
- 3
- 2
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 30
