contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.53
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 1
- 0
- 1
- 3
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 300
