contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.16
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 1
- 3
- 2
- 2000
seqLen: 189
stopOnFail: false
testLimit: 1000000000
timeout: 300
