contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.92
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 3
- 2
- 0
- 2000
seqLen: 78
stopOnFail: false
testLimit: 1000000000
timeout: 300
