contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.06
filterBlacklist: true
filterFunctions: []
mutConsts:
- 1
- 0
- 0
- 1000
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 300
