contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.39
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 3
- 3
- 1000
- 2000
seqLen: 169
stopOnFail: false
testLimit: 1000000000
timeout: 300
