contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.73
filterBlacklist: true
filterFunctions: []
mutConsts:
- 0
- 1
- 0
- 3
seqLen: 116
stopOnFail: false
testLimit: 1000000000
timeout: 300
