contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 0
- 3
- 3
- 2
seqLen: 273
stopOnFail: false
testLimit: 1000000000
timeout: 30
