contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.4
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 3
- 3
- 3
- 2
seqLen: 237
stopOnFail: false
testLimit: 1000000000
timeout: 300
