contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.93
filterBlacklist: true
filterFunctions: []
mutConsts:
- 1
- 2
- 3
- 1000
seqLen: 81
stopOnFail: false
testLimit: 1000000000
timeout: 30
