contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.65
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 0
- 2000
- 2
- 3
seqLen: 198
stopOnFail: false
testLimit: 1000000000
timeout: 300
