contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.84
filterBlacklist: true
filterFunctions:
- Test.changeOwner(address)
mutConsts:
- 2
- 0
- 3
- 1000
seqLen: 76
stopOnFail: false
testLimit: 1000000000
timeout: 300
