contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.36
filterBlacklist: true
filterFunctions: []
mutConsts:
- 2
- 1000
- 1000
- 1
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 30
