contractAddr: '0x4242'
corpusDir: corpus
coverage: true
dictFreq: 0.16
filterBlacklist: true
filterFunctions:
- Test.callPwn()
mutConsts:
- 0
- 2000
- 3
- 1
seqLen: 100
stopOnFail: false
testLimit: 1000000000
timeout: 300
